name: ai_land
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.8.0+1
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  dart_openai: ^5.1.0
  go_router: ^15.1.2
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  uuid: ^4.4.2
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  flutter_keyboard_visibility: ^6.0.0
  webview_flutter: ^4.9.0
  gap: ^3.0.1
  flutter_smart_dialog: ^4.9.8
  flutter_animate: ^4.5.0
  share_plus: ^10.0.2
  wakelock_plus: ^1.2.8
  collection: ^1.18.0
  file_picker: ^8.1.2
  flutter_markdown: ^0.7.3+1
  flutter_dotenv: ^5.2.1
  mcp_client: ^0.1.8
  mcp_llm: ^0.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13
  go_router_builder: ^2.9.0

flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - .env